# Generated by Django 3.2 on 2021-04-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210408_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blog', verbose_name="Content's blog"),
        ),
    ]
