# Generated by Django 3.2 on 2021-04-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
